version: '3.8'

x-database-variables: &database-variables
    POSTGRES_BD: Observatorio
    POSTGRES_USER: DICT
    POSTGRES_PASSWORD: qwerty2468*.

x-app-variables: &app-variables
    <<: *database-variables
    POSTGRES_HOST: postgres
    SECRET_KEY: "e154c3b8-0b5b-4dca-8f2d-08cbc07fda82"
    ALLOWED_HOSTS: "*"
    DEBUG: 0
    CSRF_COOKIE_SECURE: 1
    SESSION_COOKIE_SECURE: 1
    SECURE_HSTS_SECONDS: 31536000
    SECURE_SSL_REDIRECT: 1

services:
    postgres:
        image: postgres:13.3
        container_name: postgres_observatorio
        environment: *database-variables
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports: 
            - "5430:5432"

    django: 
        image: observatorio:0.1
        container_name: django_observatorio
        environment: *app-variables
        volumes: 
            - static:/code/static
            - .:/code
        ports: 
            - "8000:8000"
        command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn -c config/gunicorn/conf.py --bind :8000 --chdir Observatorio Observatorio.wsgi:application"
        depends_on:
            - postgres

    nginx:
        image: nginx:1.20.0
        container_name: nginx_observatorio
        ports:
            - 80:80
            - 443:443
        volumes:
            - ssl:/etc/ssl
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - static:/code/static
        depends_on:
            - django


volumes:
    .:
    postgres_data:
    ssl:
    static: