# Generated by Django 2.2.17 on 2021-01-12 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_nombbre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.BooleanField(verbose_name='Es homre?')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_centro', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Estendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_origen', models.CharField(blank=True, max_length=30, null=True)),
                ('pais_actual', models.CharField(blank=True, max_length=30, null=True)),
                ('notificacion_correo', models.BooleanField()),
                ('nivel_academico', models.IntegerField(blank=True, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Persona')),
                ('usuario_basico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=127)),
                ('especialidad', models.CharField(max_length=127)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario_Estendido')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('completado', models.BooleanField()),
                ('maestria', models.BooleanField()),
                ('titulo_maestria', models.CharField(blank=True, max_length=255, null=True)),
                ('doctorado', models.BooleanField()),
                ('titulo_doctorado', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Carrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario_Estendido')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=63)),
                ('resumen', models.CharField(blank=True, max_length=1023, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=31, null=True)),
                ('pais', models.CharField(blank=True, max_length=63, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Autor_Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.BooleanField()),
                ('autor_principal', models.BooleanField()),
                ('tutor', models.BooleanField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Documento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_amistad', models.IntegerField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario_Estendido')),
            ],
        ),
    ]
