# Generated by Django 2.2.17 on 2021-01-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210113_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='idioma',
            field=models.CharField(blank=True, choices=[('ES', 'Español'), ('EN', 'Ingles')], max_length=5, null=True),
        ),
    ]
