# Generated by Django 2.2.17 on 2021-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210113_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_estendido',
            name='nivel_academico',
            field=models.CharField(blank=True, choices=[('0', 'Ninguno'), ('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Técnico medio'), ('4', 'Pre universitario'), ('5', 'Universitario'), ('6', 'Maestría'), ('7', 'Doctorado')], max_length=1, null=True),
        ),
    ]
