# Generated by Django 2.2.17 on 2021-01-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210113_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_trabajo',
            name='cargo',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_trabajo',
            name='especialidad',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
