# Generated by Django 2.2.17 on 2021-03-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210113_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tema',
            field=models.CharField(blank=True, choices=[('Info', 'Informática'), ('Tele', 'Telecomunicaciones')], max_length=4, null=True),
        ),
    ]
